### ISSUE TITLE
Question about centroid prediction loss

### ISSUE THREAD

**Issue by DeclK** [yifanzhang713/IA-SSD#1]
Hi! I just read about this paper, IA-SSD's performance is quite amazing! 
But I got some trouble when trying to understand the centroid predction loss
![image](https://user-images.githubusercontent.com/68807035/160238196-adba3d2e-aa60-4a99-bb57-f9ff14f59a48.png)
Here are the questions:
1. What do the F+ and j mean in the formula?
2. How to understand the second term |c_ij - c_i|? Quating the paper: to minimize the uncertainty of the centroid prediction
Thanks in advance!

**Comment by DeclK** [comment]
And about the architecture of centroid-based aggregation
![image](https://user-images.githubusercontent.com/68807035/160241949-d8bbe737-c7a4-41aa-8923-9fbbe511767c.png)
is the dimension 356 correct? or it's just typing error

**Comment by yifanzhang713** [comment]
> Hi! I just read about this paper, IA-SSD's performance is quite amazing! But I got some trouble when trying to understand the centroid predction loss ![image](https://user-images.githubusercontent.com/68807035/160238196-adba3d2e-aa60-4a99-bb57-f9ff14f59a48.png) Here are the questions:
> 
> 1. What do the F+ and j mean in the formula?
> 2. How to understand the second term |c_ij - c_i|? Quating the paper: to minimize the uncertainty of the centroid prediction
>    Thanks in advance!

Hi DeclK, thanks for you attention. 

About Q1, '|F+|' here is the total number of instances (GT boxes) used to predict centroids, and the 'j' is the index of the points assigned in one instance; 
About Q2,  this part of the loss is used to promote all assigned points belonged to certain instance predict the same centroid location, which can be considered as a futher regulation of the centroid prediction.

Hope these will be helpful to you.

**Comment by yifanzhang713** [comment]
> Hi! I just read about this paper, IA-SSD's performance is quite amazing! But I got some trouble when trying to understand the centroid predction loss ![image](https://user-images.githubusercontent.com/68807035/160238196-adba3d2e-aa60-4a99-bb57-f9ff14f59a48.png) Here are the questions:
> 
> 1. What do the F+ and j mean in the formula?
> 2. How to understand the second term |c_ij - c_i|? Quating the paper: to minimize the uncertainty of the centroid prediction
>    Thanks in advance!

Hi DeclK, thanks for you attention. 

About Q1, '|F+|' here is the total number of instances (GT boxes) used to predict centroids, and the 'j' is the index of the points assigned in one instance; 
About Q2,  this part of the loss is used to promote all assignment points belonging to an instance to predict the same centroid location, which can be considered as a futher regulation of the centroid prediction.

Hope these will be helpful to you.

**Comment by yifanzhang713** [comment]
> And about the architecture of centroid-based aggregation ![image](https://user-images.githubusercontent.com/68807035/160241949-d8bbe737-c7a4-41aa-8923-9fbbe511767c.png) is the dimension 356 correct? or it's just typing error

Thank you very much for your reminder, it should be double 256 here, we will fix it in subsequent versions.

**Comment by DeclK** [comment]
Thanks for your quick reply. It's very helpful😀closing this issue
