### ISSUE TITLE
Question about the GIF figure shown in README

### ISSUE THREAD

**Issue by OuyangJunyuan** [yifanzhang713/IA-SSD#19]
How to get a series of continuous point cloud  in the KITTI dataset rather than the shuffled one like what in the training and testing sets.
many thanks!

**Comment by yifanzhang713** [comment]
Thanks for your interest. 

Yes, the results obtained on the detection dataset are all static. In fact, to better visualize the detection demo, we deploy our IA-SSD on KITTI tracking dataset.

**Comment by OuyangJunyuan** [comment]
Nice work! Thanks for your reply.

**Comment by xieqi1996** [comment]
> Thanks for your interest.
> 
> Yes, the results obtained on the detection dataset are all static. In fact, to better visualize the detection demo, we deploy our IA-SSD on KITTI tracking dataset.

How to highlight the representative point after sampling as the golden points show ? Could you please provide the visualization code ? Thanks

**Comment by OuyangJunyuan** [comment]
> > Thanks for your interest.
> > Yes, the results obtained on the detection dataset are all static. In fact, to better visualize the detection demo, we deploy our IA-SSD on KITTI tracking dataset.
> 
> How to highlight the representative point after sampling as the golden points show ? Could you please provide the visualization code ? Thanks

你可以参考一下这个
```python
    def add_keypoint(points, radius=0.05, color=None):
        for i in range(points.shape[0]):
            mesh_sphere = open3d.geometry.TriangleMesh.create_sphere(radius=radius)
            mesh_sphere.translate(points[i])
            mesh_sphere.compute_vertex_normals()
            if color is None:
                mesh_sphere.paint_uniform_color([0.1, 0.1, 0.7])
            else:
                mesh_sphere.paint_uniform_color(color)
            vis.add_geometry(mesh_sphere)
```
