### ISSUE TITLE
Effect of gt_sampling

### ISSUE THREAD

**Issue by Eaphan** [yifanzhang713/IA-SSD#20]
Thanks for your sharing. When I train without gt sampling augmentation, I noticed the performance in moderate class drop from 83.4 to 77.11. As the gt sampling doesn't affect other methods like voxel r-cnn and pv_rcnn so obviously, can you explain this phenomenon?

**Comment by yifanzhang713** [comment]
Hi @Eaphan , very thanks for your following.

I think your finding is very illuminating. Although I have not tried this analysis experiment, I guess it is related to the representation ability of the model. After all, PV-RCNN and Voxel-RCNN are both two-stage frameworks, which will have more advantages in feature learning.

Hope this can help you.
