### ISSUE TITLE
The IoU loss in IA-SSD head

### ISSUE THREAD

**Issue by itskyf** [yifanzhang713/IA-SSD#21]
Dear,

I noticed a WIP [IoU loss](https://github.com/yifanzhang713/IA-SSD/blob/78c9cf6bebf0fcc7dd17dd3e8433ce36a4c5c709/pcdet/models/dense_heads/IASSD_head.py#L34) in the code, but I could not find it in the paper. Is there any reference to implement this feature?

Btw thank you for this great work.

**Comment by yifanzhang713** [comment]
Hi, thank you for your attention, I have to apologize for my late response.

To be honest, the IoU loss in our work has potential errors in gradient backwards, so it is better not to apply it to the model.
