### ISSUE TITLE
How to calculate the instance recall rate for foreground points?

### ISSUE THREAD

**Issue by VsionQing** [yifanzhang713/IA-SSD#25]
I want to know how to get the rusult of instance recall rate

**Comment by kellen5l** [comment]
@VsionQing Hi, have you solved the problem?

**Comment by muomi** [comment]
@kellen5l @VsionQing Hi, have you solved it?

**Comment by kellen5l** [comment]
@muomi Sorry, I haven't solved it yet. Do you have any idea?
I wrote the code of calculating recall rate myself, But it is far from the results in the official paper. (Testing on the officially released pre training model)
Here is the result i got:
![2022-10-06_13-01](https://user-images.githubusercontent.com/30131620/194218376-39a81cb2-5133-4b6b-9d15-1824ec7a72c5.png)

**Comment by M0NSTERCOCO** [comment]
@kailunq Hi，how did you get the rusult of instance recall rate? Could you please share the code of calculating recall rate of points?

**Comment by BaotWang** [comment]
> Could you please share the code of calculating recall rate of points?

**Comment by BaotWang** [comment]
@kailunq hi, Could you please share the code of calculating recall rate of points?
