### ISSUE TITLE
Do you have any plan to upload config for ONCE dataset?

### ISSUE THREAD

**Issue by frogbam** [yifanzhang713/IA-SSD#3]
First of all, Thank you for your awesome works.

It seems that config file for ONCE dataset is missing.

Do you have any plan to share config file for ONCE dataset?

Thanks.

**Comment by yifanzhang713** [comment]
Thanks for your interest in our work! We are still working on the performance tuning of the ONCE dataset. The config files in this dataset will be released in the near future, please stay tuned!
