### ISSUE TITLE
cdet.ops.iou3d_nms

### ISSUE THREAD

**Issue by zhouzhenhua835** [yifanzhang713/IA-SSD#38]
Dear,
We had some problems executing the test and could not find the iou3d_nms_cuda in the file /pcdet/ops/iou3d_nms/iou3d_nms_utils.py，Is there any solution?

**Comment by yifanzhang713** [comment]
Hi @zhouzhenhua835 .Thanks for your attention. I have no idea about your detailed environment setting, but you should compile the PCDet using **python setup.py develop** first to generate a series of executable file.
