### ISSUE TITLE
 Could you release the config of ONCE dataset?

### ISSUE THREAD

**Issue by kellen5l** [yifanzhang713/IA-SSD#39]
Hi, thanks for your work.
I try to reproduce the results in the paper on ONCE dataset. Could you send me the detailed config configuration file?
Thanks !

**Comment by yifanzhang713** [comment]
Hi @kellen5l, thanks a lot for your following. Currently, I am busy with some other work and have not been able to update the ONCE dataset model in time.  But I send the recent relevant log file for you and hope this can help you. [LogFile](https://pan.baidu.com/s/1sgER-B28yvozdxq4vijVsg?pwd=slwd)

Best wishes.
