### ISSUE TITLE
KITTI Evaluation benchmark error

### ISSUE THREAD

**Issue by huangmang** [yifanzhang713/IA-SSD#46]
作者你好，我运行test 文件后生成了7518个txt预测文件,但是kitti说无法读取，反馈如下：
Thank you for participating in our evaluation!
Loading detections...
ERROR: Couldn't read: 000000.txt
An error occured while processing your results.
Please make sure that the data in your zip archive has the right format!
查看000000.txt 格式如下
Car -1 -1 -4.2805 668.2746 173.5056 725.9075 200.0053 1.4978 1.7991 4.2894 5.2318 1.5385 43.1926 -4.1612 0.9994
Car -1 -1 -1.5703 720.9199 172.1827 801.4966 245.7842 1.5590 1.6885 4.0358 3.5739 1.5445 17.4284 -1.3722 0.9965
Car -1 -1 -4.2950 734.1251 166.0022 773.6559 187.3680 1.7066 1.7468 3.9941 11.9245 1.1590 59.7687 -4.0993 0.8742
Pedestrian -1 -1 -1.9508 720.6653 154.9240 803.0667 332.3385 1.7233 0.5770 0.7711 1.4902 1.5488 7.4418 -1.7623 0.5209
Car -1 -1 0.0387 777.6276 170.5506 820.8170 189.7332 1.5686 1.6512 3.4323 15.7935 1.3799 60.2863 0.2934 0.3530
Pedestrian -1 -1 0.7366 1097.1677 123.9059 1164.2434 257.7536 1.7925 0.5584 0.5103 7.1333 1.1367 9.9742 1.3433 0.1123
Pedestrian -1 -1 -0.6670 858.1832 164.9881 889.1761 225.1737 1.7848 0.6125 0.6355 7.9094 1.5512 21.7883 -0.3237 0.1022
不知道哪里有问题。
感谢作者很nice 的工作，祝周末愉快!

**Comment by huangmang** [comment]
I have solved it

**Comment by TimGor1997** [comment]
> I have solved it

您好！我也遇到了相同的问题，请问您是怎么解决的呢？

**Comment by qifeng22** [comment]
> 作者你好，我运行test 文件后生成了7518个txt预测文件,但是kitti说无法读取，反馈如下： Thank you for participating in our evaluation! Loading detections... ERROR: Couldn't read: 000000.txt An error occured while processing your results. Please make sure that the data in your zip archive has the right format! 查看000000.txt 格式如下 Car -1 -1 -4.2805 668.2746 173.5056 725.9075 200.0053 1.4978 1.7991 4.2894 5.2318 1.5385 43.1926 -4.1612 0.9994 Car -1 -1 -1.5703 720.9199 172.1827 801.4966 245.7842 1.5590 1.6885 4.0358 3.5739 1.5445 17.4284 -1.3722 0.9965 Car -1 -1 -4.2950 734.1251 166.0022 773.6559 187.3680 1.7066 1.7468 3.9941 11.9245 1.1590 59.7687 -4.0993 0.8742 Pedestrian -1 -1 -1.9508 720.6653 154.9240 803.0667 332.3385 1.7233 0.5770 0.7711 1.4902 1.5488 7.4418 -1.7623 0.5209 Car -1 -1 0.0387 777.6276 170.5506 820.8170 189.7332 1.5686 1.6512 3.4323 15.7935 1.3799 60.2863 0.2934 0.3530 Pedestrian -1 -1 0.7366 1097.1677 123.9059 1164.2434 257.7536 1.7925 0.5584 0.5103 7.1333 1.1367 9.9742 1.3433 0.1123 Pedestrian -1 -1 -0.6670 858.1832 164.9881 889.1761 225.1737 1.7848 0.6125 0.6355 7.9094 1.5512 21.7883 -0.3237 0.1022 不知道哪里有问题。 感谢作者很nice 的工作，祝周末愉快!

你好，请问你是在kitti官网上，点击submit results进行提交的吗？我刚才试了试发现，还要填信息审核，不能提交自己的结果

**Comment by Nexus-j** [comment]
> I have solved it

您好，怎么解决的呢？

**Comment by Elvissy** [comment]
> > I have solved it
> 
> 您好！我也遇到了相同的问题，请问您是怎么解决的呢？

您好，想问一下您解决了吗

**Comment by qifeng22** [comment]
I remember this issue was caused by the ZIP file. Please zip the .txt files directly, without zipping the folder.

**Comment by Elvissy** [comment]
> I have solved it

您好，非常想知道您是怎么解决的，期望得到您的回复
